version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: source
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: gatsby-image
    versions:
    - 2.10.0
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: cypress
    versions:
    - 6.5.0
    - 6.6.0
    - 6.7.1
    - 6.8.0
    - 7.0.0
    - 7.0.1
    - 7.1.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: gatsby
    versions:
    - 2.32.10
    - 2.32.11
    - 2.32.2
    - 2.32.4
    - 2.32.6
    - 2.32.8
    - 2.32.9
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.2
    - 17.0.3
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.13.2
    - 2.13.3
    - 2.13.4
    - 2.14.0
    - 2.14.1
    - 2.14.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
