# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            John Hannagan
tagline:          The Jekyll Butler
url:              http://johnhannagan.com
paginate:         4
baseurl:          /
author:
  name:           John Hannagan
  url:            http://johnhannagan.com
  email:          Nope@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

#navbar pages
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
  
 #defaults
 defaults: 
	-
		scope:
			type: "post"
		values:
			comments: true