# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            John Hannagan
url:              http://johnhannagan.com
paginate:         4
baseurl:          /
author:
  name:           John Hannagan
  url:            http://johnhannagan.com
  email:          Nope@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

#navbar pages
pages_list:
  Posts: '/archive'
  Photography: 'https://www.flickr.com/photos/77862175@N06/'
  Feed: '/atom.xml'

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      comments: true