# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            John Hannagan
url:              http://johnhannagan.com
paginate:         3
baseurl:          /
author:
  name:           John Hannagan
  url:            http://johnhannagan.com
  email:          Nope@gmail.com
  
# Set up photo blog collections
collections:
- photoblogs
  
#prose.io settings
prose:
  siteurl: http://johnhannagan.com
  media: public
  metadata:
    _posts:
      - name: "layout"
        field:
          label: "layout"
          element: "text"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Code"
              value: "code"
            - name: "Travel"
              value: "travel"

