# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            John Hannagan
url:              http://johnhannagan.com
paginate:         3
baseurl:          /
author:
  name:           John Hannagan
  url:            http://johnhannagan.com
  email:          Nope@gmail.com

#navbar pages
pages_list:
  Posts: '/archive'
  Photos: '/photos'

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      comments: true
