# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            John Hannagan
url:              http://johnhannagan.com
paginate:         3
baseurl:          /
author:
  name:           John Hannagan
  url:            http://johnhannagan.com
  email:          Nope@gmail.com

#navbar pages
pages_list:
  Posts: '/archive'
