name: Deploy

on:
  push:
    branches: [source]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy
        uses: actions/setup-node@v1
      - run: yarn
      - run: yarn build
      - run: yarn deploy
        env:
          CI: true
