name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Percy Visual Regressions
        uses: percy/snapshot-action@v0.3.1
        with:
          build-directory: "public"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run develop
          wait-on: http://localhost:8000
